name: CI

on: [push, pull_request]

jobs:
  verify-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: make lint spec
      - run: crystal tool format --check src/ spec/ example/

  verify-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install crystal
      - run: shards install
      - run: make spec
